name: SIT Deployment

on:
  workflow_dispatch:

jobs:
  build-and-deploy-sit:
    runs-on: ubuntu-latest
    env:
      PLATFORM_USERNAME: ${{ secrets.PLATFORM_USERNAME }}
      PLATFORM_PASSWORD: ${{ secrets.PLATFORM_PASSWORD }}
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Cache Dependencies
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: maven
    
    - name: Build with maven
      run: mvn -B clean package -s settings.xml
    
    - name: Upload artifact 
      uses: actions/upload-artifact@v3
      with:
          name: artifacts
          path: target/*.jar
    
    - name: Download artifact
      uses: actions/download-artifact@v3
      with:
        name: artifacts
    
    - name: Deploy to SIT
      run: mvn deploy -DmuleDeploy -DskipTests --file pom.xml -s settings.xml
